### PR TITLE
Three kinds of python exercises and public example course

### PR DESCRIPTION
**Pull request by BTWS2**
These examples will also be visible in the public example course:
https://dodona.ugent.be/nl/courses/358/

### CODE REVIEW

**Comment by BTWS2** [comment]
In my PR I changed the existing `echo` exercise to `echo-python-input`. Can the PR be merged if I undo those changes or create a new exercise for `echo-python-input` instead? I think it's important teachers have an example of the three most common kinds of Python tests.

**Comment by bmesuere** [comment]
As I told in a comment somewhere else, we'll merge the example exercises from https://github.com/dodona-edu/dodona-docs/tree/master/sample/judge and reorganize this repo in the near future.

**Comment by bmesuere** [comment]
@BTWS @BTWS2 I think this can be closed because of the new exercises?

**Comment by BTWS2** [comment]
I would like to add the two simple exercises `echo-function-print` and `echo-function-return` in a separate PR because it shows a simple markdown example and the usage of labels for an exercise. I think there is no example for functions with print right now.

**Comment by charvp** [comment]
I'm not sure how relevant another markdown example will be; most exercises in the repository use markdown for their descriptions (ISBN-MD being the most prominent example). Evaluating print in functions in Python is indeed something # not demonstrated yet, so feel free to make a PR for that (or edit this one).

`visibility` has been deprecated in favour of `access` since Dodona 2.4.

No webhook has been configured for the repository, so no automatic updates will happen. In my personal opinion, it also doesn't make much sense to add this repository to (production) Dodona. Most exercises are made to demonstrate usage of a certain feature and don't actually have good testcases or a good description. The fully developed exercises are already in Dodona, since they were copied from (our) exercise repositories.

**Comment by BTWS2** [comment]
In the documentation we recommend Markdown which is more accessible, but all examples of the Python folder are in html (except `ISBN-MD`). Maybe some exercises with can be converted to Markdown instead of adding a new Markdown example? If you agree I will make a PR for this. You can close this PR, I will make a new one for evaluating print in functions.

I will make a PR to change `visibility` to `acces` in the example here: https://dodona-edu.github.io/nl/references/exercise-config/#oefening.

If a teacher wants to know how to design (new) exercises, having an example course with the same examples does add value. The teacher can interact with the examples before making his/her own repository or course. It's difficult to know how the exercise will be/look, if they can only can see the source code. Having both, allows them to compare and understand how it works by comparing the the exercise and source code. The course also demonstrates how the markdown/html is rendered. If there is one course with all the examples, teachers don't have to search for the exercise in Dodona. My intention with the example course is not to have good testcases or a good description. The sole purpose is to show how making exercises works. I can make the example course based on a fork (with the same content) of this repository and linking to the original repository.

**Comment by charvp** [comment]
> In the documentation we recommend Markdown which is more accessible, but all examples of the Python folder are in html (except `ISBN-MD`). Maybe some exercises with can be converted to Markdown instead of adding a new Markdown example? If you agree I will make a PR for this. You can close this PR, I will make a new one for evaluating print in functions.

Sure, converting most exercises to markdown seems fine to me (not all though, some HTML examples should still be there).
 
> I will make a PR to change `visibility` to `acces` in the example here: https://dodona-edu.github.io/nl/references/exercise-config/#oefening.

Ah yes, these examples should indeed be updated (note that the actual text refers to `access`, not `visibility`). Note that `access` is written with two s's.

> If a teacher wants to know how to design (new) exercises, having an example course with the same examples does add value. The teacher can interact with the examples before making his/her own repository or course. It's difficult to know how the exercise will be/look, if they can only can see the source code. Having both, allows them to compare and understand how it works by comparing the the exercise and source code. The course also demonstrates how the markdown/html is rendered. If there is one course with all the examples, teachers don't have to search for the exercise in Dodona. My intention with the example course is not to have good testcases or a good description. The sole purpose is to show how making exercises works. I can make the example course based on a fork (with the same content) of this repository and linking to the original repository.

If we do this (which I'm still not entirely convinced about), both the Dodona repository and the example course should be managed by the core Dodona team IMO.

**Comment by BTWS2** [comment]
> Ah yes, these examples should indeed be updated (note that the actual text refers to access, not visibility). Note that access is written with two s's.

I made a PR: https://github.com/dodona-edu/dodona-edu.github.io/pull/92

> If we do this (which I'm still not entirely convinced about), both the Dodona repository and the example course should be managed by the core Dodona team IMO.

Thats ok for me. If the Dodona core members register in the [example course](https://dodona.ugent.be/nl/courses/358/) I will promote them to course administrators. You can also make a new course if you want.

You can close this PR.

**Pull request closed without merging**
